### ISSUE TITLE
Spark notebook not working on AWS EMR

### ISSUE THREAD

**Issue by oscarcastaneda** [big-data-europe/docker-hadoop-spark-workbench#11]
After starting the HDFS/Spark Workbench, and opening up any notebook on Spark Notebook, I get the following error:

"Dead Kernel: The kernel has died, and the automatic restart has failed. It is possible the kernel cannot be restarted. If you are not able to restart the kernel, you will still be able to save the notebook, but running code will no longer work until the notebook is reopened."

Selecting "Manual Restart" results in "No kernel" and as a result no cells in the notebook can be run.

Same setup on Mac OS X works like a charm. How can I make this work on AWS EMR? Thanks!

**Comment by earthquakesan** [comment]
@oscarcastaneda sorry for late answer, can you please provide config you are using for AWS? Are you using the same docker-compose.yml or customize it somehow?
