### ISSUE TITLE
Hue is not able to login

### ISSUE THREAD

**Issue by snowf0x** [big-data-europe/docker-hadoop-spark-workbench#12]
With master branch code, Hue throws exception when login with user 'hue', as stated in here http://www.big-data-europe.eu/scalable-sparkhdfs-workbench-using-docker/

namenode          | 16/07/29 15:45:04 WARN security.UserGroupInformation: No groups available for user hue
namenode          | 16/07/29 15:45:04 WARN security.UserGroupInformation: No groups available for user hue
namenode          | 16/07/29 15:45:04 INFO namenode.FSEditLog: Number of transactions: 2 Total time for transactions(ms)
: 4 Number of transactions batched in Syncs: 0 Number of syncs: 2 SyncTimes(ms): 1
hdfsfb            | 172.18.0.1 - - [29/Jul/2016 08:45:05] "POST /accounts/login/ HTTP/1.1" 302 -
hdfsfb            | 172.18.0.1 - - [29/Jul/2016 08:45:05] "GET / HTTP/1.1" 500 -
hdfsfb            | Traceback (most recent call last):
hdfsfb            |   File "/opt/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/contrib/static
files/handlers.py", line 67, in __call__
hdfsfb            |     return self.application(environ, start_response)
hdfsfb            |   File "/opt/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/handlers/
wsgi.py", line 206, in __call__
hdfsfb            |     response = self.get_response(request)
hdfsfb            |   File "/opt/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/handlers/
base.py", line 194, in get_response
hdfsfb            |     response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
hdfsfb            |   File "/opt/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/handlers/
base.py", line 229, in handle_uncaught_exception
hdfsfb            |     return debug.technical_500_response(request, *exc_info)
hdfsfb            |   File "/opt/hue/build/env/lib/python2.7/site-packages/django_extensions-1.5.0-py2.7.egg/django_exte
nsions/management/technical_response.py", line 5, in null_technical_500_response
hdfsfb            |     six.reraise(exc_type, exc_value, tb)
hdfsfb            |   File "/opt/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/handlers/
base.py", line 112, in get_response
hdfsfb            |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
hdfsfb            |   File "/opt/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/transaction
.py", line 371, in inner
hdfsfb            |     return func(*args, **kwargs)
hdfsfb            |   File "/opt/hue/desktop/core/src/desktop/views.py", line 283, in index
hdfsfb            |     return redirect(reverse('about:index'))
hdfsfb            |   File "/opt/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/urlresolv
ers.py", line 532, in reverse
hdfsfb            |     key)
hdfsfb            | NoReverseMatch: u'about' is not a registered namespace

**Comment by earthquakesan** [comment]
@snowf0x sorry for late response, was on vacations -)

The last line fails, not the first one (the first one just gives you a warning). You need to specifically open /home path like:
```
http://docker-host-ip:8088/home
```
Please refer to this issue: https://github.com/big-data-europe/docker-hadoop-spark-workbench/issues/9
