### ISSUE TITLE
TaskSchedulerImpl: Initial job has not accepted any resources

### ISSUE THREAD

**Issue by yuandra** [big-data-europe/docker-hadoop-spark-workbench#14]
Tried running both docker-compose-hive.yml and docker-compose.yml on a 4 core 8gb VM running Ubuntu 14.
- Spark notebook always waiting for kernel to start
- Tried connecting to spark instance via a scala program using a spark driver (scala 2.10, spark 1.6.2) in the local machine (need to open port 7077 in the docker.yml file first). 
  Connected successfully, worker is detected on the spark UI (port 8080). 
- Tried creating a data file using a text file on the local machine, worker seems to be running. However receive message  "WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources"  every 15 seconds. 
- Check the spark UI and shown worker is running however when the job seems to be not executed. Hangs without any progress. It is the only application in the spark cluster.

Possibility : 
1.  not enough resources (previously it was 2 core, 8gb and I increased it 4 core, 8gb). Only running a single worker and a single app.. There should be enough resources I think.. I set the spark conf to only run single core with 1gb of ram per worker
2. the spark worker cannot communicate with the spark master (spark master successfully detected the worker in the UI, and when tried to see the worker details it is redirected to the worker local ip that are not accessible from the outside).. Thinking this might be the problem ?

**Comment by earthquakesan** [comment]
Hi @yuandra!

Thanks for the input! First of all I apologize, docker-compose-hive.yml is not really tested thoroughly. I am working on Hive-enabled version, for now please use docker-compose.yml.

Can you provide me more details on how you tried to launch your spark app?
Also, there was a problem for submitting Spark applications/uploading HDFS files when forwarding the ports, because spark-master/hdfs-namenode essentially redirected the client to workers/datanodes, which got no exposed ports.

Here is how you can do this: https://medium.com/@ivanermilov/hi-martin-5d6ad8989f48#.3xuz9h1kc

In case you want local dev setup, I suggest something like this: https://github.com/earthquakesan/hdfs-spark-hive-dev-setup

**Comment by yuandra** [comment]
hi @earthquakesan ! Thanks for the reply !

I'll try the makefile after this - still running some test on the docker images.

So I tried deploying it both on local and on a VM, both using docker-compose.yml with port 7070 open

On local (running on a 4 core / 16 gb)
- can access spark ui, hue, hadoop ui, and notebook.  Tried notebook core/simple-spark and it run fine
- can connect to spark using a scala app as a driver to port 7070. 
Tried running it from  both IDE and using spark submit
- there is no "WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources" every 15 seconds"
- can run operations, however got error when writing into the HDFS - the error is the worker node cannot connect to the HDFS ip address (the same error that you mentioned in your reply)

On a Ubuntu VM hosted on azure (running 4 core / 16gb)
- can access spark ui, hue, hadoop ui, and notebook. Tried notebook core/simple-spark and it run fine
- can connect to spark using a scala app as a driver to port 7070.
Tried running it from both IDE and using spark submit
-always receive  "WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources" every 15 seconds"

Sample code of the driver app - running Scala 2.10.6 and spark-core.2.10 , 1.6.2

Object SparkTest {

def main(args: Array[String]): Unit = {
  
val tSparkConf = new SparkConf()
      .setMaster("spark://x.x.x.x:7077")
      .setAppName("spark-test")

    val tSparkContext = new SparkContext(tSparkConf)

    val f = tSparkContext.textFile("hdfs://x.x.x.x:8020/user/hue/output.json")

    val counts = f.flatMap(line => line.split(" "))
      .map(word => (word, 1))
      .reduceByKey(_ + _)

    counts.saveAsTextFile("hdfs://x.x.x.x:8020/user/hue/output_new")

    tSparkContext.stop() 

}
}

**Comment by earthquakesan** [comment]
@yuandra hi again!

I migrated all the images to Java 8. Also there is a new Spark 2.0.0 there. Can you please check if issue still persists? Use the following docker-compose file:
https://github.com/big-data-europe/docker-hadoop-spark-workbench/blob/master/docker-compose-java8.yml

**Comment by earthquakesan** [comment]
@yuandra did you manage to solve the issue? I would recommend using docker-spark dockers from this repo for production setup: https://github.com/big-data-europe/docker-spark Feel free to reopen issue on that repo.

**Comment by ycli12** [comment]
I occurred with this isssue and found that it is really out of resources.
Solution：
1、Increase machine cores or memory
2、decrease resource requirements when you submit application like below
bin/run-example –executor-memory 2g –num-executors 1 –executor-cores 1 GroupByTest 3 4 100 2
Soulution2 is more practical in most cases.
