### ISSUE TITLE
How to enable Pyspark in Jupyter Notebook

### ISSUE THREAD

**Issue by agmistry** [big-data-europe/docker-hadoop-spark-workbench#18]
I am a relative nubie to Docker containers and have found your project very useful. I want to develop Python using SparkSQL Notebooks and unfortunately the Notebook in this bundle only supports Scala. How can I modify this build to incorporate support for Python notebooks and SparkSQL?

Any assistance would be appreciated

Regards

Anant

**Comment by earthquakesan** [comment]
Spark notebook supports only Scala --> https://github.com/andypetrella/spark-notebook

What you need to do is to add Jupyter service (it is already packed into the docker image as I can see https://github.com/jupyter/docker-stacks/tree/master/all-spark-notebook) into docker-compose.yml and figure out how to connect it to HDFS/Spark.

**Comment by earthquakesan** [comment]
@agmistry did you succeed in integration python notebooks?
