### ISSUE TITLE
Steps compatible to Windows?

### ISSUE THREAD

**Issue by prashantladha** [big-data-europe/docker-hadoop-spark-workbench#19]
Hi,
Are these below steps compatible on Windows Dockers?

    docker network create hadoop
    docker-compose up -d
    docker-compose scale spark-worker=3

Few issues that I observed were:
1. The docker-compose scale did not work for me unless I killed the Docker containers and restart them.
2. The "data" directory was not created automatically.
3. below command did not work, when executed from data folder
docker run -it --rm --env-file=../hadoop.env --volume $(pwd):/data --net hadoop uhopper/hadoop hadoop fs -put vannbehandlingsanlegg.csv /user/root

**Comment by earthquakesan** [comment]
Sorry, got no windows machine to try it out =\

Can you please contribute a separate branch if you figure out how to run it on windows?

**Comment by earthquakesan** [comment]
@prashantladha hi! Any success running the workbench on windows?
