### ISSUE TITLE
Hue is not working

### ISSUE THREAD

**Issue by nicolasjustSnoopConsulting** [big-data-europe/docker-hadoop-spark-workbench#21]
Hi
I only execute "docker-compose up -d". I do not make any changes
The Hue (HDFS Filebrowser) is not working. After login I get this error

![image](https://cloud.githubusercontent.com/assets/8170600/25498451/5f77b952-2b5e-11e7-9a37-5effb960d557.png)

How can i solve it?

Thanks

**Comment by earthquakesan** [comment]
This is known problem, the solution is in the README.md file:
```
When opening Hue, you might encounter NoReverseMatch: u'about' is not a registered namespace error after login. I disabled 'about' page (which is default one), because it caused docker container to hang. To access Hue when you have such an error, you need to append /home to your URI: http://docker-host-ip:8088/home
```
