### ISSUE TITLE
Binding 8081 port error when I execute scale up

### ISSUE THREAD

**Issue by VijayQin** [big-data-europe/docker-hadoop-spark-workbench#24]
➜  docker-hadoop-spark-workbench git:(master) sudo docker-compose up -d
Creating network "dockerhadoopsparkworkbench_default" with the default driver
Creating spark-notebook ...
Creating spark-master ...
Creating dockerhadoopsparkworkbench_hue_1 ...
Creating namenode ...
Creating spark-notebook
Creating spark-master
Creating dockerhadoopsparkworkbench_hue_1
Creating namenode ... done
Creating dockerhadoopsparkworkbench_datanode_1 ...
Creating dockerhadoopsparkworkbench_hue_1 ... done
Creating dockerhadoopsparkworkbench_datanode_1
Creating dockerhadoopsparkworkbench_spark-worker_1 ... done
➜  docker-hadoop-spark-workbench git:(master) sudo docker-compose scale spark-worker=3
Starting dockerhadoopsparkworkbench_spark-worker_1 ... done
Creating dockerhadoopsparkworkbench_spark-worker_2 ...
Creating dockerhadoopsparkworkbench_spark-worker_3 ...
Creating dockerhadoopsparkworkbench_spark-worker_2 ... error
Creating dockerhadoopsparkworkbench_spark-worker_3 ... error

ERROR: for dockerhadoopsparkworkbench_spark-worker_2  Cannot start service spark-worker: driver failed programming external connectivity on endpoint dockerhadoopsparkworkbench_spark-worker_2 (796ee234433b58f170caabee79d04644276ebc04f9eb8509f7ffd0390dca6658): Bind for 0.0.0.0:8081 failed: port is already allocated

ERROR: for dockerhadoopsparkworkbench_spark-worker_3  Cannot start service spark-worker: driver failed programming external connectivity on endpoint dockerhadoopsparkworkbench_spark-worker_3 (925cb4a1c2bfe6132d39b58862dfdd1d5b15feb08f37cdb6070a4432c43da8d1): Bind for 0.0.0.0:8081 failed: port is already allocated
ERROR: Cannot start service spark-worker: driver failed programming external connectivity on endpoint dockerhadoopsparkworkbench_spark-worker_2 (796ee234433b58f170caabee79d04644276ebc04f9eb8509f7ffd0390dca6658): Bind for 0.0.0.0:8081 failed: port is already allocated
➜  docker-hadoop-spark-workbench git:(master)

![image](https://cloud.githubusercontent.com/assets/6880815/26717465/1304b05c-47b0-11e7-9e90-f6f464ec8b44.png)

It was caused by spark_worker_1 had already occupied the port 8081, thus spark_work_2 and other workers failed to bind the port.
What should I do now? What is the port 8081 used for？

**Comment by fdiblen** [comment]
I have just created a new pull request to solve this issue. Please have a look.

**Comment by VijayQin** [comment]
Yes, it works by remove the port 8081 using from spark-work.

And it seems better after adding load blance component into the project.


________________________________
发件人: Faruk D. <notifications@github.com>
发送时间: 2017年6月2日 18:49
收件人: big-data-europe/docker-hadoop-spark-workbench
抄送: Vijay Qin; Author
主题: Re: [big-data-europe/docker-hadoop-spark-workbench] Binding 8081 port error when I execute scale up (#24)


I have just created a new pull request to solve this issue. Please have a look.

―

**Comment by JMLamodiere** [comment]
FYI, when https://github.com/docker/compose/issues/5230 is fixed, there will be another solution : using the port range notation : `8081-8090:8081` . BUT the choosen range would put a max limit on the scaling. Ex : `8081-8090` means `spark-worker=10` max.

#25 is not affected by this limitation.

**Comment by earthquakesan** [comment]
The best way to scale I found so far is behind traefik proxy, see example setup [here](https://github.com/big-data-europe/docker-hadoop-spark-workbench/tree/master/swarm)
