### ISSUE TITLE
latest version of hue and hue.ini in volume

### ISSUE THREAD

**Issue by antonkulaga** [big-data-europe/docker-hadoop-spark-workbench#29]
Current hue version has a lot of issues for me: it is outdated and partially broken. In our lab we have our own docker-compose configuration that uses latest hue 4. I am ready to contribute by updating hue here but for this, I will probably need to include hue.ini file in hue volume.

**Comment by earthquakesan** [comment]
Hi @antonkulaga!
Can you please create pull request, we can discuss it then. Thanks a lot!

**Comment by antonkulaga** [comment]
I put it here https://github.com/big-data-europe/docker-hadoop-spark-workbench/pull/30
I used default gethue/hue repo there, but if needed I can make a PR to your hue container (that is quite bugy now) to update it to the latest version.
