### ISSUE TITLE
Any way to run this in swarm mode?

### ISSUE THREAD

**Issue by nirobayo** [big-data-europe/docker-hadoop-spark-workbench#31]
Hi,

This configuration and images worked very well for me. But still, being only able to deploy on one physical machine is an issue. The docker-compose files are version 2, not compatible with swarm mode. Is there something I am missing out, or is this meant to be used on only one physical machine?

Thanks in advance!

P.D.: For scaling I am using pull request #25

**Comment by earthquakesan** [comment]
Hi @nirobayo!

Sure there is: https://github.com/big-data-europe/docker-hadoop-spark-workbench/tree/master/swarm

The setup I created will deploy datanode on each of the swarm nodes (mode: global) and only 1 namenode. You can also use constraints/affinity to modify the deployment schema.

P.S. I am not sure if scaling is really important in case of hadoop/spark as there is no reason to run more than one datanode/worker per node. Thus, global mode does the trick.

**Comment by nirobayo** [comment]
Thanks. You even made a new configuration! Still, I am having issues running it.

I activated swarm mode and added a second machine _worker1_ to it. When deploying, everything on the local machine goes fine, but it errors on _worker1_ (trying to restart it indefinitely). The description is quite short:

`standard_init_linux_go:187: exec user process caused "no such file or directory"`

I am suspecting, since this error is not raised on my local machine, that it has to do with files that only the local machine has. Possibly _hadoop.env_? I am lacking some clues.

**Comment by earthquakesan** [comment]
@nirobayo can you create a snippet with a full log for both spark-master and spark-worker.

Environment file should be no problem, it is evaluated by swarm manager and then injected into all of the images. I have tested the setup with 3 ubuntu boxes (using kvm for virtualization) and docker 17.06, got no problem running it.

**Comment by nirobayo** [comment]
@earthquakesan Wow, I did not explain myself completely fine. I never started Spark. The error ocurred while starting Hadoop, and only on the datanode container not deployed on the swarm manager.

I am trying to get a log, but found no way to do it (_hadoop logs_ gives the message I send in the previous post). I tried to start a datanode locally within _worker1_ with success, so something must have gone awry in the communication between swarm manager and worker (and it is pretty fast, only requires a few seconds for the containers to fail).

I will post a log or any additional info I get when I find it.

Thanks for your help!

**Comment by nirobayo** [comment]
I am getting something like this on my worker node daemon:

![error](https://user-images.githubusercontent.com/12829700/30865933-37995d0e-a2d8-11e7-8732-8bd164b916af.PNG)

I've checked that network connectivity is up on ports 2377 tcp, 7946 tcp/udp, 4789 udp and also protocol esp, bidirectional, of course. Also the network appears on _worker1_ once deploy starts (and when removed is removed from the worker's list).

I am also getting an error when stopping _dockerd_ on _worker1_, which is something like

`docker was able to connect <manager-real-ip> but other probes failed, network may be misconfigured`

**Comment by earthquakesan** [comment]
@nirobayo here seems to be related issue: https://github.com/moby/moby/issues/31698

**Comment by nirobayo** [comment]
@earthquakesan Ok, I found out what the issue was. I'm not planning to ever use CentOS as a Docker host again. I'm with Debian now.
It's working, but I'm not able to use the web UIs. I can't access them from the host machine. Anyways, I think the configuration is fine. I'm closing this as the main issue is solved, we can comment further anyways.
