### ISSUE TITLE
Override SPARK_MASTER and SPARK_MASTER_PORT env variables

### ISSUE THREAD

**Issue by eschizoid** [big-data-europe/docker-hadoop-spark-workbench#32]
Would it be possible to override `SPARK_MASTER` and `SPARK_MASTER_PORT` env variables by just defining them in `hadoop-hive.env` file?

**Comment by earthquakesan** [comment]
As long as you include env file in the docker-compose as:
```
    env_file:
      - ./hadoop-hive.env
```
You can override any of the env vars.

**Comment by eschizoid** [comment]
feel free to close the ticket
