### ISSUE TITLE
How do i get my hadoop home directory?

### ISSUE THREAD

**Issue by akinmail** [big-data-europe/docker-hadoop-spark-workbench#35]
When i start the docker container, where will my hadoop home directory be?. What will be the path of the hadoop directory. I want to point sqoop to it and sqoop needs to know the hadoop directory of the hadoop installation on my system

**Comment by earthquakesan** [comment]
Hi @akinmail!

The data is bound to docker volumes and can be found in your local folder:
```
./data/namenode:/hadoop/dfs/name
./data/datanode:/hadoop/dfs/data
```
Basically it is in the ./data folder (relative to the folder where you run docker-compose up). Read [docker-compose.yml](https://github.com/big-data-europe/docker-hadoop-spark-workbench/blob/master/docker-compose.yml) for more details.

If you mean home folder in HDFS filesystem, then you will need to create a user and create a folder there. The default endpoint is hdfs://namenode:8020, see [hadoop.env](https://github.com/big-data-europe/docker-hadoop-spark-workbench/blob/master/docker-compose.yml) for configuration details.

**Comment by akinmail** [comment]
No i meant, what folder on the base container in which hadoop was extracted to(installed to)? Anyway, i followed the dependency of the dockerfile up till the base container and i was able to find (this){https://hub.docker.com/r/bde2020/hadoop-base/~/dockerfile/}. The hadoop is downloaded and extracted into the opt folder. I assume this will be the HADOOP_HOME

**Comment by earthquakesan** [comment]
@akinmail all the Dockerfiles are in this [repo](https://github.com/big-data-europe/docker-hadoop). Check the "base" folder in particular.

**Comment by akinmail** [comment]
There this env exposed in that same file named HADOOP_PREFIX. i believe this is what i was searching for

**Comment by earthquakesan** [comment]
You can see that HADOOP_PREFIX points to [hadoop installation folder](https://github.com/big-data-europe/docker-hadoop/blob/9af1f86bdbd0c0a8c3a9511820ee2f1c5386be53/base/Dockerfile#L62)

P.S. Hint: git branches correspond to docker hub tags
