### ISSUE TITLE
sparkContext not found in spark notebook

### ISSUE THREAD

**Issue by Henrilin28** [big-data-europe/docker-hadoop-spark-workbench#36]
I tried to start the script in core/simple but the error shows that 
`<console>:15: error: not found: value sparkContext
       sparkContext.getConf.toDebugString
       ^
<console>:12: error: not found: value globalScope
       globalScope.sparkContext.setJobGroup("cell-958C08DD7D9E4D528E649879CA2912E4", "run-1510003533026: sparkContext.getConf.toDebugString")
       ^
`
I wondering what happens? 

I use docker-compose.yml to start up the service

**Comment by earthquakesan** [comment]
@Henrilin28 I suggest using Apache Zeppelin as Spark Notebooks can be quite difficult to handle sometime. See example setup [here](https://github.com/big-data-europe/docker-hadoop-spark-workbench/tree/master/swarm)
