### ISSUE TITLE
 command: ["./wait-for-it.sh"] for swarm mode

### ISSUE THREAD

**Issue by antonkulaga** [big-data-europe/docker-hadoop-spark-workbench#39]
As I understood from the issue tracker Docker team does not want to add depends_on support to the swarm. In such case it will make sense to add https://github.com/vishnubob/wait-for-it to check the datanode always starts after namenode

**Comment by earthquakesan** [comment]
@antonkulaga that's indeed the case, I have injected wait-for-it script into [hadoop on this branch](https://github.com/big-data-europe/docker-hadoop/tree/2.0.0-hadoop2.7.4-java8). I will put an action to update docker-hadoop-spark-workbench, I have very clear idea on how to run it with swarm without issues. Check out this [distributed hbase setup](https://github.com/big-data-europe/docker-hbase/tree/master/distributed) for example.

**Comment by antonkulaga** [comment]
I do not see wait script there but I see SERVICE_PRECONDITION. How does it work? It does not look like docker-compose standard instruction. Have you also check that it works in swarm mode? (I see that some things in swarm mode are not supported but no warnings are shown)

**Comment by earthquakesan** [comment]
@antonkulaga it's not standard docker thing, it's an ENV variable. entrypoint bash script is polling services from that variable. See entrypoint [here](https://github.com/big-data-europe/docker-hadoop/blob/2.0.0-hadoop2.7.4-java8/base/entrypoint.sh)
