### ISSUE TITLE
Switch spark-notebook to apache zeppelin

### ISSUE THREAD

**Issue by earthquakesan** [big-data-europe/docker-hadoop-spark-workbench#40]

**Comment by antonkulaga** [comment]
Why do you need this? Is not Spark-notebook better?

**Comment by earthquakesan** [comment]
@antonkulaga at one point I had to use custom library with spark-notebook. I could not figure out how to add custom jar, so that it is exposed to the notebooks. In Apache Zeppelin it is straight forward.

Additional cons are:
* Apache project
* More than 1 maintainer

For Apache Zeppelin with custom lib, see an example [here](https://github.com/SANSA-Stack/SANSA-Notebooks/blob/develop/docker-compose.yml). Basically, it is possible to run zeppelin with SPARK_SUBMIT_OPTIONS, and those support adding any jar files to the spark job.

**Comment by antonkulaga** [comment]
I dunnot, I had no issues with custom dependencies and I have a lot. I think adding dependencies is describe at https://github.com/spark-notebook/spark-notebook/blob/master/docs/metadata.md

**Comment by earthquakesan** [comment]
@antonkulaga if you can share your experience, would be nice. My requirements for spark-notebook with custom dependencies were:
1. Inject dependencies via configuration (not from graphical UI)
2. Dependencies can come from both maven and as local jar files

Thanks a lot in advance!

**Comment by antonkulaga** [comment]
@earthquakesan Regarding dependencies from different libs and repos, they are written just inside snpb files https://raw.githubusercontent.com/antonkulaga/bigdata-docker/master/notebooks/genome-searcher/genome-searcher-genome-searcher.snb.ipynb In particular:
```json
"customRepos":["comp-bio-aging % default % https://dl.bintray.com/comp-bio-aging/main/","denigma % default % https://dl.bintray.com/denigma/denigma-releases/"],
"customDeps":["comp.bio.aging %% adam-playground % 0.0.7-M4","com.crealytics %% spark-excel % 0.8.3"],
"customImports":["import org.bdgenomics.adam.rdd.ADAMContext._ \n","import org.bdgenomics.adam.models._ \n","import org.bdgenomics.adam.rdd.feature._ \n","import org.bdgenomics.formats.avro._ \n"]
```

If you want to include any dependencies that are not available in public repos, you can include them as volume. For instance, here ( https://github.com/antonkulaga/bigdata-docker/tree/master/conf/notebook/repos ) I have some custom builds of adam and other libraries in my spark-notebook as part of the docker-compose configuration

**Comment by earthquakesan** [comment]
@antonkulaga nice! Thanks for sharing your solution here!
