### ISSUE TITLE
Question: how can i run hdfs command line commands such as "hdfs dfs fs -ls"

### ISSUE THREAD

**Issue by tomer-ben-david** [big-data-europe/docker-hadoop-spark-workbench#41]
Question please: how can i run hdfs command line commands such as `hdfs dfs fs -ls`?

**Comment by earthquakesan** [comment]
Hi @tomer-ben-david!

you can find an example in this [Makefile](https://github.com/big-data-europe/docker-hadoop/blob/2.0.0-hadoop2.7.4-java8/Makefile).
