### ISSUE TITLE
Q: How can you scale out on multiple hosts?

### ISSUE THREAD

**Issue by cmantas** [big-data-europe/docker-hadoop-spark-workbench#42]
Hello.

This is a very useful setup -  well done.
Is it possible to scale out on multiple hosts, for a trully distributed cluster?

If yes, could you provide some info on how to do it?
I can write it up, if I figure it out,  in  step-by-step manner an add it in documentation on a PR if you'd like that.

**Comment by earthquakesan** [comment]
Hi @cmantas,

I have assembled [HDFS+YARN+HBase setup for distributed cluster](https://github.com/big-data-europe/docker-hbase/tree/master/distributed). Here, only Spark needs to be modified to be able to deploy all the things on Docker Swarm.

P.S. It is on my TODO list as well.

**Comment by cmantas** [comment]
Very nice @earthquakesan.
Not familiar with Dropbox, but I might try and fool around with it a bit and get back to you if it takes me anywhere. 
Thnx and congrats on the project.

**Comment by earthquakesan** [comment]
@cmantas, why Dropbox? I don't understand.

btw, I am on it atm, will push the setup today or tomorrow.

**Comment by cmantas** [comment]
Sorry, I meant *Docker

**Comment by earthquakesan** [comment]
@cmantas,

example setup can be found [here](https://github.com/big-data-europe/docker-hadoop-spark-workbench/tree/master/swarm). If you have any questions, feel free to open another issue.
