### ISSUE TITLE
links to any official mailing lists /chats/etc.

### ISSUE THREAD

**Issue by antonkulaga** [big-data-europe/docker-hadoop-spark-workbench#43]
@earthquakesan is there any official gitter/googlegroup whatever to discuss workbench? At https://www.big-data-europe.eu I see only official email

**Comment by earthquakesan** [comment]
@antonkulaga, no, we only have official mail. I've just created gitter:

https://gitter.im/big-data-europe/docker-hadoop-spark-workbench
