### ISSUE TITLE
java.net.UnknownHostException: namenode

### ISSUE THREAD

**Issue by C0mmander198** [big-data-europe/docker-hadoop-spark-workbench#45]
Hi,
I'm running a scala spark job. I created a uber jar and used spark-submit to move it to the docker spark master:
`spark-submit --class "myclass" --master spark://localhost:7077 target/myjob-1.0-SNAPSHOT.jar`

It executes well, but when trying to write to HDFS I get the following error:
> Exception in thread "main" java.lang.IllegalArgumentException: java.net.UnknownHostException: namenode

In the spark job I'm using this line to write to hdfs
`myrdd.saveAsTextFile("hdfs://namenode:8020/myfile")`

Which host/port do I have to use to make this work? I tried localhost and nothing, but without success. Where can I set the DNS of my namenode?

**Comment by earthquakesan** [comment]
@C0mmander198, I have created an example on how to run [an uber jar with the workbench](https://github.com/big-data-europe/docker-hadoop-spark-workbench/tree/master/example).

Another possibility is to use [Spark templates](https://github.com/big-data-europe/docker-spark/tree/master/template/java).

Have fun! -)
