### ISSUE TITLE
Global Values not found

### ISSUE THREAD

**Issue by smrazaabbas** [big-data-europe/docker-hadoop-spark-workbench#50]
Hi, 
I have setup Spark master, worker nodes via docker in this repo. 
Upon running the sample code, or any code for that matter, Spark notebook throws the following error:

error: not found: value globalScope
error: not found: value SparkSession

**Comment by earthquakesan** [comment]
Hi,

I have switched from spark-notebook to Apache Zeppelin. There is more discussion here: https://github.com/big-data-europe/docker-hadoop-spark-workbench/issues/40 (also pointers for working setup with spark-notebook).

**Comment by smrazaabbas** [comment]
Great. Thanks, I'll look into it.
